//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//using System.Net;

using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.ServiceModel.Security;

namespace Flyadeal.Interceptors.Yakeen4Flyadeal {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class Yakeen4FlydealFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CommonErrorObject commonErrorObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public CommonErrorObject commonErrorObject {
            get {
                return this.commonErrorObjectField;
            }
            set {
                this.commonErrorObjectField = value;
                this.RaisePropertyChanged("commonErrorObject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class CommonErrorObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByVisaResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByVisaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chargeCodeField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        private string visaIssueYearField;
        
        private string visaNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("chargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string visaIssueYear {
            get {
                return this.visaIssueYearField;
            }
            set {
                this.visaIssueYearField = value;
                this.RaisePropertyChanged("visaIssueYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string visaNumber {
            get {
                return this.visaNumberField;
            }
            set {
                this.visaNumberField = value;
                this.RaisePropertyChanged("visaNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", ConfigurationName="Yakeen4Flyadeal.Yakeen4Flydeal")]
    public interface Yakeen4Flydeal {
        
        // CODEGEN: Parameter 'AlienInfoByVisaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4FlydealFault), Action="", Name="Yakeen4FlydealFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="AlienInfoByVisaResult")]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse getAlienInfoByVisa(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse> getAlienInfoByVisaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa request);
        
        // CODEGEN: Parameter 'AlienInfoByPassportResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4FlydealFault), Action="", Name="Yakeen4FlydealFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="AlienInfoByPassportResult")]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse getAlienInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse> getAlienInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport request);
        
        // CODEGEN: Parameter 'AlienInfoByIqamaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4FlydealFault), Action="", Name="Yakeen4FlydealFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="AlienInfoByIqamaResult")]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse getAlienInfoByIqama(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse> getAlienInfoByIqamaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama request);
        
        // CODEGEN: Parameter 'CitizenInfoByPassportResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4FlydealFault), Action="", Name="Yakeen4FlydealFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CitizenInfoByPassportResult")]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse getCitizenInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse> getCitizenInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport request);
        
        // CODEGEN: Parameter 'CitizenInfoByIDResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4FlydealFault), Action="", Name="Yakeen4FlydealFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CitizenInfoByIDResult")]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse getCitizenInfoByID(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse> getCitizenInfoByIDAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByVisa", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByVisa {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaRequest AlienInfoByVisaRequest;
        
        public getAlienInfoByVisa() {
        }
        
        public getAlienInfoByVisa(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaRequest AlienInfoByVisaRequest) {
            this.AlienInfoByVisaRequest = AlienInfoByVisaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByVisaResponse", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByVisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaResult AlienInfoByVisaResult;
        
        public getAlienInfoByVisaResponse() {
        }
        
        public getAlienInfoByVisaResponse(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaResult AlienInfoByVisaResult) {
            this.AlienInfoByVisaResult = AlienInfoByVisaResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByPassportRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chargeCodeField;
        
        private short nationalityCodeField;
        
        private string passportNumberField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("chargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public short nationalityCode {
            get {
                return this.nationalityCodeField;
            }
            set {
                this.nationalityCodeField = value;
                this.RaisePropertyChanged("nationalityCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string passportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
                this.RaisePropertyChanged("passportNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByPassportResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByPassport", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByPassport {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportRequest AlienInfoByPassportRequest;
        
        public getAlienInfoByPassport() {
        }
        
        public getAlienInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportRequest AlienInfoByPassportRequest) {
            this.AlienInfoByPassportRequest = AlienInfoByPassportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByPassportResponse", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByPassportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportResult AlienInfoByPassportResult;
        
        public getAlienInfoByPassportResponse() {
        }
        
        public getAlienInfoByPassportResponse(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportResult AlienInfoByPassportResult) {
            this.AlienInfoByPassportResult = AlienInfoByPassportResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByIqamaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chargeCodeField;
        
        private string dateOfBirthField;
        
        private string iqamaNumberField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("chargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string iqamaNumber {
            get {
                return this.iqamaNumberField;
            }
            set {
                this.iqamaNumberField = value;
                this.RaisePropertyChanged("iqamaNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class alienInfoByIqamaResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByIqama", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByIqama {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaRequest AlienInfoByIqamaRequest;
        
        public getAlienInfoByIqama() {
        }
        
        public getAlienInfoByIqama(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaRequest AlienInfoByIqamaRequest) {
            this.AlienInfoByIqamaRequest = AlienInfoByIqamaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlienInfoByIqamaResponse", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getAlienInfoByIqamaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaResult AlienInfoByIqamaResult;
        
        public getAlienInfoByIqamaResponse() {
        }
        
        public getAlienInfoByIqamaResponse(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaResult AlienInfoByIqamaResult) {
            this.AlienInfoByIqamaResult = AlienInfoByIqamaResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class citizenInfoByPassportRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chargeCodeField;
        
        private string dateOfBirthField;
        
        private string passportNumberField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("chargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string passportNumber {
            get {
                return this.passportNumberField;
            }
            set {
                this.passportNumberField = value;
                this.RaisePropertyChanged("passportNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class citizenInfoByPassportResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfoByPassport", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfoByPassport {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportRequest CitizenInfoByPassportRequest;
        
        public getCitizenInfoByPassport() {
        }
        
        public getCitizenInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportRequest CitizenInfoByPassportRequest) {
            this.CitizenInfoByPassportRequest = CitizenInfoByPassportRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfoByPassportResponse", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfoByPassportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportResult CitizenInfoByPassportResult;
        
        public getCitizenInfoByPassportResponse() {
        }
        
        public getCitizenInfoByPassportResponse(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportResult CitizenInfoByPassportResult) {
            this.CitizenInfoByPassportResult = CitizenInfoByPassportResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class citizenInfoByIDRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chargeCodeField;
        
        private string dateOfBirthField;
        
        private string ninField;
        
        private string passwordField;
        
        private string referenceNumberField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chargeCode {
            get {
                return this.chargeCodeField;
            }
            set {
                this.chargeCodeField = value;
                this.RaisePropertyChanged("chargeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
                this.RaisePropertyChanged("dateOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nin {
            get {
                return this.ninField;
            }
            set {
                this.ninField = value;
                this.RaisePropertyChanged("nin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNumber {
            get {
                return this.referenceNumberField;
            }
            set {
                this.referenceNumberField = value;
                this.RaisePropertyChanged("referenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/")]
    public partial class citizenInfoByIDResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int logIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int logId {
            get {
                return this.logIdField;
            }
            set {
                this.logIdField = value;
                this.RaisePropertyChanged("logId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfoByID", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfoByID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDRequest CitizenInfoByIDRequest;
        
        public getCitizenInfoByID() {
        }
        
        public getCitizenInfoByID(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDRequest CitizenInfoByIDRequest) {
            this.CitizenInfoByIDRequest = CitizenInfoByIDRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitizenInfoByIDResponse", WrapperNamespace="http://yakeen4flydeal.yakeen.elm.com/", IsWrapped=true)]
    public partial class getCitizenInfoByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://yakeen4flydeal.yakeen.elm.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDResult CitizenInfoByIDResult;
        
        public getCitizenInfoByIDResponse() {
        }
        
        public getCitizenInfoByIDResponse(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDResult CitizenInfoByIDResult) {
            this.CitizenInfoByIDResult = CitizenInfoByIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Yakeen4FlydealChannel : Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Yakeen4FlydealClient : System.ServiceModel.ClientBase<Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal>, Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal
    {

        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Yakeen4FlydealClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Yakeen4FlydealClient);
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Yakeen4FlydealClient))
            {
                //return new System.ServiceModel.EndpointAddress("https://yakeen-piloting.eserve.com.sa/Yakeen4Flydeal/Yakeen4Flydeal");
                return new System.ServiceModel.EndpointAddress("https://yakeen.eserve.com.sa/Yakeen4Flydeal/Yakeen4Flydeal");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Yakeen4FlydealClient))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Yakeen4FlydealClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Yakeen4FlydealClient);
        }

        public Yakeen4FlydealClient() :
                base(Yakeen4FlydealClient.GetDefaultBinding(), Yakeen4FlydealClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Yakeen4FlydealClient.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
            //var certFile = "yakeen-piloting.eserve.com.sa.crt";
            var certFile = "YAKEEN_CERT.crt"; // Prod
            var certPath = "./Certificates/" + certFile;
#if DEBUG
            certPath = "../Flyadeal.Interceptors/bin/Debug/netcoreapp2.0/Certificates/" + certFile;
#endif
            this.ChannelFactory.Credentials.ClientCertificate.Certificate = new X509Certificate2(certPath);
            this.ChannelFactory.Credentials.ServiceCertificate.SslCertificateAuthentication = new X509ServiceCertificateAuthentication();
            this.ChannelFactory.Credentials.ServiceCertificate.SslCertificateAuthentication.CertificateValidationMode = X509CertificateValidationMode.None;
            ServicePointManager.ServerCertificateValidationCallback = (a, b, c, d) => true;
        }

        public Yakeen4FlydealClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Yakeen4FlydealClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yakeen4FlydealClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Yakeen4FlydealClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public enum EndpointConfiguration
        {
            BasicHttpBinding_Yakeen4FlydealClient,
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByVisa(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa request) {
            return base.Channel.getAlienInfoByVisa(request);
        }
        
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaResult getAlienInfoByVisa(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaRequest AlienInfoByVisaRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa();
            inValue.AlienInfoByVisaRequest = AlienInfoByVisaRequest;
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse retVal = ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByVisa(inValue);
            return retVal.AlienInfoByVisaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse> Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByVisaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa request) {
            return base.Channel.getAlienInfoByVisaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisaResponse> getAlienInfoByVisaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByVisaRequest AlienInfoByVisaRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByVisa();
            inValue.AlienInfoByVisaRequest = AlienInfoByVisaRequest;
            return ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByVisaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport request) {
            return base.Channel.getAlienInfoByPassport(request);
        }
        
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportResult getAlienInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportRequest AlienInfoByPassportRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport();
            inValue.AlienInfoByPassportRequest = AlienInfoByPassportRequest;
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse retVal = ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByPassport(inValue);
            return retVal.AlienInfoByPassportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse> Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport request) {
            return base.Channel.getAlienInfoByPassportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassportResponse> getAlienInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByPassportRequest AlienInfoByPassportRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByPassport();
            inValue.AlienInfoByPassportRequest = AlienInfoByPassportRequest;
            return ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByPassportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByIqama(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama request) {
            return base.Channel.getAlienInfoByIqama(request);
        }
        
        public Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaResult getAlienInfoByIqama(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaRequest AlienInfoByIqamaRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama();
            inValue.AlienInfoByIqamaRequest = AlienInfoByIqamaRequest;
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse retVal = ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByIqama(inValue);
            return retVal.AlienInfoByIqamaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse> Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getAlienInfoByIqamaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama request) {
            return base.Channel.getAlienInfoByIqamaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqamaResponse> getAlienInfoByIqamaAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.alienInfoByIqamaRequest AlienInfoByIqamaRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getAlienInfoByIqama();
            inValue.AlienInfoByIqamaRequest = AlienInfoByIqamaRequest;
            return ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getAlienInfoByIqamaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getCitizenInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport request) {
            return base.Channel.getCitizenInfoByPassport(request);
        }
        
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportResult getCitizenInfoByPassport(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportRequest CitizenInfoByPassportRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport();
            inValue.CitizenInfoByPassportRequest = CitizenInfoByPassportRequest;
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse retVal = ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getCitizenInfoByPassport(inValue);
            return retVal.CitizenInfoByPassportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse> Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getCitizenInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport request) {
            return base.Channel.getCitizenInfoByPassportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassportResponse> getCitizenInfoByPassportAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByPassportRequest CitizenInfoByPassportRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByPassport();
            inValue.CitizenInfoByPassportRequest = CitizenInfoByPassportRequest;
            return ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getCitizenInfoByPassportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getCitizenInfoByID(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID request) {
            return base.Channel.getCitizenInfoByID(request);
        }
        
        public Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDResult getCitizenInfoByID(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDRequest CitizenInfoByIDRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID();
            inValue.CitizenInfoByIDRequest = CitizenInfoByIDRequest;
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse retVal = ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getCitizenInfoByID(inValue);
            return retVal.CitizenInfoByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse> Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal.getCitizenInfoByIDAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID request) {
            return base.Channel.getCitizenInfoByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByIDResponse> getCitizenInfoByIDAsync(Flyadeal.Interceptors.Yakeen4Flyadeal.citizenInfoByIDRequest CitizenInfoByIDRequest) {
            Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID inValue = new Flyadeal.Interceptors.Yakeen4Flyadeal.getCitizenInfoByID();
            inValue.CitizenInfoByIDRequest = CitizenInfoByIDRequest;
            return ((Flyadeal.Interceptors.Yakeen4Flyadeal.Yakeen4Flydeal)(this)).getCitizenInfoByIDAsync(inValue);
        }
    }
}
